;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   qui jun 8 2023
; Processor: PIC16F84A
; Compiler:  MPASM (MPLAB)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================


#include 	p16f84a.inc                ; Include register definition file

#define 	banco0		bcf STATUS, RP0
#define		banco1		bsf STATUS, RP0

controle 	equ			0x0c
contador	equ			0x0d	

#define		display		PORTB
#define		botao		PORTA,RA0
#define		flag 		controle,0



;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================


; Reset Vector
			org 		0x00 
			goto  		configura
			
			org			0x04
			retfie

;====================================================================
; CODE SEGMENT
;====================================================================

configura
			banco1
			movlw 		D'1'
			movwf		TRISA
			movlw		D'0'
			movwf		TRISB
			movlw		B'10000000'
			movwf		OPTION_REG
			movlw		D'0'
			movwf		INTCON
			banco0
			movlw		D'0'
			movwf		contador
			movwf		display
			
zera_flag
			bcf			flag
			
inicio
			btfsc		botao					;pressionado? (é 0?)
			goto		zera_flag				;não, reseta flag
			btfsc		flag					;sim, flag? (é 0?)
			goto		inicio					;não,
			bsf			flag					;sim, seta flag
			incf		contador, F				;incrementa contador
			movlw		D'10'
			subwf		contador, W				;w = 10 - contador
			btfsc		STATUS, Z				;w = 0, ou seja armazena é maior que 9
			clrf		contador				;zera contador
			call		mostra_display
			goto		inicio
			
mostra_display
			movf		contador, W
			movwf		display
			return
			



;====================================================================
      END
